//
//  AppLanguage.swift
//  PlantviaApp
//
//  Created by Nizamettin Şimşek on 29.05.2026.
//

import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case turkish = "tr"
    
    var id: String { rawValue }
    
    var title: String {
        switch self {
            case .english: return "English"
            case .turkish: return "Türkçe"
        }
    }
    
    static var current: AppLanguage {
        AppLanguage(rawValue: UserDefaults.standard.string(forKey: "appLanguage") ?? AppLanguage.english.rawValue) ?? .english
    }
}

enum L10n {
    static func text(_ key: String, language: AppLanguage = .current) -> String {
        guard language == .turkish else { return key }
        return turkish[key] ?? key
    }
    
    static func format(_ key: String, _ arguments: CVarArg..., language: AppLanguage = .current) -> String {
        String(format: text(key, language: language), arguments: arguments)
    }
    
    private static let turkish: [String: String] = [
        "Today": "Bugün",
        "Plants": "Bitkiler",
        "Calendar": "Takvim",
        "Profile": "Profil",
        "Get Started": "Başla",
        "Continue": "Devam",
        "Update required": "Güncelleme gerekli",
        "Update now": "Şimdi güncelle",
        "A new version is required to continue using Plantvia.": "Plantvia kullanmaya devam etmek için yeni sürüm gerekli.",
        "Minimum supported version: %@": "Minimum desteklenen sürüm: %@",
        "Track your plants beautifully": "Bitkilerini zarifçe takip et",
        "Keep every plant's location, species, care notes, and watering rhythm in one place.": "Her bitkinin konumu, türü, bakım notu ve sulama düzeni tek yerde.",
        "Never miss watering": "Sulamayı kaçırma",
        "See what needs watering today, this week, and this month with a calendar-first view.": "Bugün, bu hafta ve bu ay sulanacak bitkileri takvim hissiyle gör.",
        "AI plant assistant": "AI bitki asistanı",
        "Upload a photo and get Turkish care suggestions about leaves, soil, light, and watering.": "Fotoğraf yükle, yaprak, toprak, ışık ve bakım hakkında Türkçe öneri al.",
        "Premium care experience": "Premium bakım deneyimi",
        "Unlimited plants, AI assistant, advanced history, and an ad-free experience.": "Sınırsız bitki, AI bitki asistanı, gelişmiş geçmiş ve reklamsız kullanım.",
        "Give your plants a premium care rhythm.": "Bitkilerine premium bir bakım ritmi kazandır.",
        "Email": "E-posta",
        "Password": "Şifre",
        "Log in": "Giriş yap",
        "Forgot password": "Şifremi unuttum",
        "Don't have an account? Register": "Hesabın yok mu? Kayıt ol",
        "Account": "Hesap",
        "Register": "Kayıt ol",
        "Create account": "Kayıt ol",
        "Your email address": "E-posta adresin",
        "Sent": "Gönderildi",
        "Send reset link": "Sıfırlama bağlantısı gönder",
        "This screen calls the backend service layer for password reset flow.": "Bu ekran şifre sıfırlama akışı için backend servis katmanını çağırır.",
        "Close": "Kapat",
        "Welcome, %@": "Merhaba, %@",
        "Premium": "Premium",
        "Free": "Free",
        "We prepared a calm and clear care plan for your plants today.": "Bugün bitkilerin için sakin ama net bir bakım planı hazırladık.",
        "Healthy": "Sağlıklı",
        "Needs watering": "Sulama bekliyor",
        "Overdue": "Gecikti",
        "Plants to water today": "Bugün sulanacaklar",
        "All calm today": "Bugün sakin",
        "No plants need watering right now.": "Sulama bekleyen bitki yok.",
        "Quick actions": "Hızlı aksiyonlar",
        "Add plant": "Bitki ekle",
        "Ask AI": "AI’ya sor",
        "All": "Tümü",
        "Plant not found": "Bitki bulunamadı",
        "This plant may have been deleted or is no longer available.": "Bu bitki silinmiş veya artık erişilebilir olmayabilir.",
        "Try changing your search or filter.": "Aramayı veya filtreyi değiştir.",
        "Search plant or species": "Bitki veya tür ara",
        "My Plants": "Bitkilerim",
        "Search, filter, and keep every plant's rhythm visible.": "Ara, filtrele ve her bitkinin bakım ritmini görünür tut.",
        "%d days": "%d günde bir",
        "%d days left": "%d gün kaldı",
        "Care rhythm": "Bakım ritmi",
        "Care is overdue": "Bakım gecikti",
        "Water today": "Bugün sula",
        "Next watering: %@": "Sonraki sulama: %@",
        "Basic information": "Temel bilgiler",
        "Create a care rhythm that is easy to follow.": "Takip etmesi kolay bir bakım ritmi oluştur.",
        "Required": "Zorunlu",
        "Plant name": "Bitki adı",
        "Species": "Tür",
        "Location": "Konum",
        "Photo": "Fotoğraf",
        "Choose photo": "Fotoğraf seç",
        "Photo selected": "Fotoğraf seçildi",
        "Start tracking plants, watering rhythm, and care history.": "Bitkileri, sulama ritmini ve bakım geçmişini takip etmeye başla.",
        "Watering routine": "Sulama rutini",
        "Daily": "Günlük",
        "Every %d days": "Her %d günde bir",
        "Notes": "Notlar",
        "Save": "Kaydet",
        "OK": "Tamam",
        "Missing information": "Eksik bilgi",
        "Could not save plant": "Bitki kaydedilemedi",
        "Please enter a plant name.": "Lütfen bitki adını gir.",
        "Free plant limit reached": "Free bitki limiti doldu",
        "Free plan supports up to %d plants. Upgrade to Premium for unlimited plants.": "Free plan en fazla %d bitki destekler. Sınırsız bitki için Premium’a geç.",
        "Free plan supports up to 3 plants. Upgrade to Premium for unlimited plants.": "Free plan en fazla 3 bitki destekler. Sınırsız bitki için Premium’a geç.",
        "Plant creation requires an internet connection.": "Bitki eklemek için internet bağlantısı gerekir.",
        "Plant editing requires an internet connection.": "Bitki düzenlemek için internet bağlantısı gerekir.",
        "Plant deletion requires an internet connection.": "Bitki silmek için internet bağlantısı gerekir.",
        "Update plant": "Bitkiyi güncelle",
        "Edit plant": "Bitkiyi düzenle",
        "Delete plant?": "Bitki silinsin mi?",
        "Delete": "Sil",
        "Cancel": "Vazgeç",
        "This plant and its watering history will be deleted.": "Bu bitki ve sulama geçmişi silinecek.",
        "Could not delete plant": "Bitki silinemedi",
        "Offline watering will sync when internet is back.": "Offline sulama kaydı internet gelince senkronize edilecek.",
        "Sync pending": "Senkron bekliyor",
        "Unknown species": "Tür belirtilmedi",
        "New Plant": "Yeni Bitki",
        "Watered today": "Bugün suladım",
        "Ask AI about this plant": "AI’ya bu bitkiyi sor",
        "Photo, watering, soil, and leaf clues in one answer.": "Fotoğraf, sulama, toprak ve yaprak ipuçları tek cevapta.",
        "Care suggestion for %@?": "%@ için bakım önerisi verir misin?",
        "Plant detail": "Bitki detayı",
        "Last watered": "Son sulama",
        "Last watered: %@": "Son sulama: %@",
        "Next watering": "Sonraki sulama",
        "No notes yet.": "Henüz not yok.",
        "Selected day": "Seçilen gün",
        "Care calendar": "Bakım takvimi",
        "See watering rhythm by day and catch overdue care early.": "Sulama ritmini gün gün gör ve geciken bakımı erkenden yakala.",
        "No watering": "Sulama yok",
        "No task is planned for this day.": "Bu gün için planlanan görev görünmüyor.",
        "AI Plant Assistant": "AI Bitki Asistanı",
        "AI requires internet connection": "AI için internet bağlantısı gerekir",
        "Photo analysis and care answers are available when you are back online.": "Fotoğraf analizi ve bakım cevapları tekrar online olduğunda kullanılabilir.",
        "Hi, send your plant photo and question. I can prepare safe care suggestions for watering, light, soil, and leaves.": "Merhaba, bitkinin fotoğrafını ve sorunu gönder. Sulama, ışık, toprak ve yaprak durumu için güvenli bakım önerileri hazırlayayım.",
        "I am Plantvia AI. Upload a clear plant photo and ask your question; I will review visible leaves, soil, light clues, watering routine, and care risks without making a definitive diagnosis.": "Ben Plantvia AI. Net bir bitki fotoğrafı yükle ve sorunu sor; görünen yaprakları, toprağı, ışık ipuçlarını, sulama rutinini ve bakım risklerini kesin teşhis iddiası olmadan değerlendireyim.",
        "Upload a photo and ask for focused care guidance.": "Fotoğraf yükle ve odaklı bakım önerisi iste.",
        "Ask about your plant": "Bitkin hakkında soru sor",
        "AI is analyzing...": "AI analiz ediyor...",
        "Upload photo": "Fotoğraf yükle",
        "Make sure leaves, soil, and the overall plant are clear.": "Yaprak, toprak ve genel görünüm net olsun.",
        "Why are the leaves yellow?": "Yapraklar neden sarardı?",
        "Is the soil dry?": "Toprağı kuru mu?",
        "How much water should I give?": "Ne kadar su vermeliyim?",
        "Is this plant healthy?": "Bu bitki sağlıklı mı?",
        "Suggestions": "Öneriler",
        "Suggestions: %@": "Öneriler: %@",
        "Confidence: %@": "Güven: %@",
        "AI Plant Assistant is Premium only": "AI Bitki Asistanı Premium’a özel",
        "Photo-based plant analysis, care suggestions, and smart Q&A are available only for Premium users.": "Fotoğrafla bitki analizi, bakım önerileri ve akıllı soru-cevap desteği yalnızca Premium kullanıcılar için kullanılabilir.",
        "Leaf and soil feedback from photos": "Fotoğraf üzerinden yaprak ve toprak yorumu",
        "Safe care suggestions and warnings": "Güvenli bakım önerileri ve uyarılar",
        "Ad-free advanced care experience": "Reklamsız ve gelişmiş bakım deneyimi",
        "Go Premium": "Premium’a geç",
        "Plantvia Premium": "Plantvia Premium",
        "More plants, more analysis, and an ad-free care experience.": "Daha fazla bitki, daha fazla analiz ve reklamsız bakım deneyimi.",
        "Unlimited plants": "Sınırsız bitki",
        "AI plant analysis": "AI bitki analizi",
        "Advanced calendar": "Gelişmiş takvim",
        "Watering history": "Sulama geçmişi",
        "Smart suggestions": "Akıllı öneriler",
        "Ad-free usage": "Reklamsız kullanım",
        "Restore purchases": "Satın alımları geri yükle",
        "Purchase could not be completed. Please try again.": "Satın alma tamamlanamadı. Lütfen tekrar dene.",
        "Purchases could not be restored. Please try again.": "Satın alımlar geri yüklenemedi. Lütfen tekrar dene.",
        "Purchase was cancelled.": "Satın alma iptal edildi.",
        "Restore was cancelled.": "Geri yükleme iptal edildi.",
        "Continue with %@": "%@ ile devam et",
        "Best value": "En avantajlı",
        "Intro: %@": "Tanıtım: %@",
        "Flexible monthly access": "Esnek aylık erişim",
        "Best for long-term plant care": "Uzun vadeli bitki bakımı için en iyi seçenek",
        "Buy selected plan: %@": "Seçili planı satın al: %@",
        "Manage subscription": "Aboneliği yönet",
        "RevenueCat SDK is not linked": "RevenueCat SDK bağlı değil",
        "Resolve the RevenueCat Swift Package in Xcode to display the hosted paywall.": "Hosted paywall ekranını göstermek için RevenueCat Swift Package bağımlılığını Xcode içinde çöz.",
        "Resolve the RevenueCatUI Swift Package in Xcode to display Customer Center.": "Customer Center ekranını göstermek için RevenueCatUI Swift Package bağımlılığını Xcode içinde çöz.",
        "Premium status": "Premium durumu",
        "Save profile": "Profili kaydet",
        "Could not update profile": "Profil güncellenemedi",
        "Profile update requires an internet connection.": "Profil güncellemek için internet bağlantısı gerekir.",
        "Nickname must be at least 2 characters.": "Nickname en az 2 karakter olmalı.",
        "Profile updated": "Profil güncellendi",
        "Your profile information was saved.": "Profil bilgilerin kaydedildi.",
        "Status": "Durum",
        "Plan": "Plan",
        "Preferences": "Tercihler",
        "Theme": "Tema",
        "Language": "Dil",
        "Premium notifications": "Premium bildirimler",
        "Daily care notification": "Günlük bakım bildirimi",
        "Notification time": "Bildirim saati",
        "Enable notifications with Premium": "Premium ile bildirimleri aç",
        "Help": "Yardım",
        "About": "Hakkında",
        "Grow Up Your Plants": "Bitkilerini Büyüt",
        "Why Plantvia?": "Neden Plantvia?",
        "Plantvia simplifies plant care with calendar tracking, watering history, and AI-assisted suggestions.": "Plantvia, bitki bakımını takvim, sulama geçmişi ve AI destekli önerilerle sadeleştiren bir MVP uygulamasıdır.",
        "Plantvia simplifies plant care with calendar tracking, watering history, smart reminders, and AI-assisted suggestions.": "Plantvia; takvim takibi, sulama geçmişi, akıllı hatırlatmalar ve AI destekli önerilerle bitki bakımını sadeleştirir.",
        "What you can do": "Neler yapabilirsin",
        "Track every plant's care rhythm": "Her bitkinin bakım ritmini takip et",
        "See watering days on a clear calendar": "Sulama günlerini net bir takvimde gör",
        "Review watering history and notes": "Sulama geçmişini ve notlarını incele",
        "Use AI analysis with Premium": "Premium ile AI analizini kullan",
        "App information": "Uygulama bilgileri",
        "Version": "Sürüm",
        "Default language": "Varsayılan dil",
        "Made for": "Hazırlandığı cihaz",
        "iPhone": "iPhone",
        "Log out": "Çıkış yap",
        "AdMob Banner": "AdMob Banner",
        "Google Mobile Ads SDK is not linked yet.": "Google Mobile Ads SDK henüz projeye bağlanmadı.",
        "AdMob Test Banner": "AdMob Test Banner",
        "Ads are hidden with Premium.": "Premium ile reklamlar gizlenir.",
        "Session was not found.": "Oturum bulunamadı.",
        "AI analysis requires an active session.": "AI analizi için oturum bulunamadı.",
        "AI analysis could not be completed.": "AI analizi tamamlanamadı.",
        "AI analysis could not be completed right now. Please try again later.": "AI analizi şu anda tamamlanamadı. Lütfen daha sonra tekrar dene.",
        "AI Plant Assistant is available for Premium users only.": "AI Bitki Asistanı yalnızca Premium kullanıcılar için kullanılabilir.",
        "Question is required.": "Soru alanı zorunludur.",
        "Daily AI and care notifications are Premium only.": "Günlük AI ve bakım bildirimleri Premium kullanıcılara özeldir.",
        "Notification permission is required for Premium reminders.": "Premium hatırlatmalar için bildirim izni gerekir.",
        "Today's plant care is ready": "Bugünkü bitki bakımın hazır",
        "Your plants may need you today. Check your care plan.": "Bitkilerin bugün seni bekliyor olabilir. Bakım planını kontrol et.",
        "The expected response was not received from the server.": "Sunucudan beklenen cevap alınamadı.",
        "Photo could not be uploaded.": "Fotoğraf yüklenemedi.",
        "Email or password is incorrect.": "E-posta veya şifre hatalı.",
        "Please check the fields and try again.": "Lütfen alanları kontrol edip tekrar dene.",
        "Your session has expired. Please log in again.": "Oturumun sona erdi. Lütfen tekrar giriş yap.",
        "You do not have permission for this action.": "Bu işlem için yetkin yok.",
        "The requested record could not be found.": "İstenen kayıt bulunamadı.",
        "Something went wrong. Please try again later.": "Bir şeyler ters gitti. Lütfen daha sonra tekrar dene.",
        "Living Room": "Salon",
        "Kitchen": "Mutfak",
        "Balcony": "Balkon",
        "Bedroom": "Yatak Odası",
        "Office": "Çalışma Odası",
        "Monthly": "Aylık",
        "Yearly": "Yıllık"
    ]
}

extension String {
    var localized: String {
        L10n.text(self)
    }
}
